// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8pE-CU25mliwyswhZiJtzxPLBJDPgNE',
    appId: '1:792394984488:android:964143ec0222989773591d',
    messagingSenderId: '792394984488',
    projectId: 'mycaloriesmate-f4a4e',
    databaseURL: 'https://mycaloriesmate-f4a4e-default-rtdb.firebaseio.com',
    storageBucket: 'mycaloriesmate-f4a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-Cks65oC8BQ3bzqjwxBB3mwd-_j9SCo',
    appId: '1:792394984488:ios:4078ce2ad275192d73591d',
    messagingSenderId: '792394984488',
    projectId: 'mycaloriesmate-f4a4e',
    databaseURL: 'https://mycaloriesmate-f4a4e-default-rtdb.firebaseio.com',
    storageBucket: 'mycaloriesmate-f4a4e.appspot.com',
    iosClientId: '792394984488-c08j1n8n2equnpsgd4vg4ou4m2fbbp7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriesMate',
  );
}
